# Generated by Django 5.0.6 on 2025-06-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_alumnos_options_alumnos_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
