# Generated by Django 5.0.6 on 2025-06-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_alumnos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='imagen',
        ),
    ]
