# Generated by Django 5.0.6 on 2025-06-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentario'},
        ),
    ]
